services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - SA_PASSWORD=Password132@
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    networks:
      - ims-net

  ims-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ims-api
    depends_on:
      - sqlserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Default=Server=sqlserver;Database=Ims;User=sa;Password=Password132@;Trusted_Connection=False;TrustServerCertificate=True;
    ports:
      - "5000:5000"
    networks:
      - ims-net

networks:
  ims-net:
    driver: bridge